#!/bin/bash
# Description: Tests the ex04 of the project cpp01

#Colors
RESET='\033[0m'
DODGERBLUE1="\033[38;5;33m"
ORANGERED1="\033[38;5;202m"
SPRINGGREEN5="\033[38;5;41m"
GREENYELLOW="\033[38;5;154m"
DEEPPINK6="\033[38;5;125m"
DARKSLATEGRAY2="\033[38;5;87m"
CHARTREUSE6="\033[38;5;64m"
SLATEBLUE1="\033[38;5;99m"

# Functions
getAction() {
	text="$1"

	read -p "Press any key to continue..." key
	echo "$key"
}

startTest() {
	testName="$1"
	fileToModify="$2"
	ori="$3"
	subs="$4"

	echo ""
	echo "~~~~~~~~~~~~~~~~~~~~~~"
	echo "$DODGERBLUE1$testName:$RESET \"./sed $fileToModify \""
	echo ""
	echo "\"remplacing $SLATEBLUE1-$ori-$RESET whith $DARKSLATEGRAY2-$subs-$RESET\""
	./Sed "$fileToModify" "$ori" "$subs" > /dev/null
	echo "$ORANGERED1""Original file: $RESET"
	/bin/cat "$fileToModify"
	echo ""
	echo "$CHARTREUSE6""Modified file: $RESET"
	/bin/cat "$fileToModify".replace
	echo "~~~~~~~~~~~~~~~~~~~~~~"
	echo ""
	getAction > /dev/null
	echo ""
	echo ""
}

# Compile project
echo "Compiling project"
make

# Start testing
startTest "Classic test #1" "./testFiles/classic" "que" "YOUHOU"
startTest "Both strings empty test #2" "./testFiles/bothStringEmpty " "" ""
startTest "One string empty #3" "./testFiles/oneStringEmpty" "" "YOUHOU"
startTest "The other string empty #4" "./testFiles/theOtherEmpty" "que" ""
startTest "One letter test #5" "./testFiles/oneLetter" "a" "z"
startTest "One line test #6" "./testFiles/justOneLine" "just" "it's never"
startTest "Empty file test #7" "./testFiles/empty" "a" "b"
startTest "Baba test #8" "./testFiles/baba" "B" "a"
startTest "Sneaky test #9" "./testFiles/sneaky" "fafa" "BAGUETTE"
startTest "Special char test #10" "./testFiles/specialCharacters" "Š" "⊕"
startTest "Very long text test #11" "./testFiles/veryLong" "B" "a"
startTest "Folder test #12" "./testFiles/folder.txt" "que" "YOUHOU"

echo ""
echo "THE END"
echo ""